#if defined _cb_constant_included
 #endinput
#endif
#define _cb_constant_included

#define INVALID_CLIENT 0
#define MAX_HEALTH 100
#define TIMER_HEAL_PLAYER_FLAGS TIMER_FLAG_NO_MAPCHANGE
#define HEALTH_SOUND "items/smallmedkit1.wav"
#define HEALTH_LOW_SOUND "common/warning.wav"
#define PRELOAD_YES true
#define TEAM_ALLIES 2
#define MEDIC_VERSIONS_AMOUNT 2
#define MEDIC_VERSION_FIRST 0
#define MEDIC_VERSION_SECOND 1
#define PLAY_MEDIC_SOUND_YES true
#define PLAY_MEDIC_SOUND_NO false
#define PLAYER_DEAD 0
#define COOKIE_MAX_SIZE 4
#define COOKIE_DEFAULT_VALUE false
#define NULL_TERMINATOR '\0'
#define SOUND_NOTICE_YES "1"
#define SOUND_NOTICE_NO "0"
#define MENU_HEADER "Medic sound notice"
#define ITEM_MAX_SIZE 32
#define ITEM_ON "Turn on notice"
#define ITEM_OFF "Turn off notice"
#define CONFIG_CREATE_YES true
